### ISSUE TITLE
Vloopers: sporadic KeynotFoundExceptions leading to unresponsiveness

### ISSUE THREAD

**Issue by tonikone** [mdotstrange/NightmarePuppeteerPublic#28]
I can't get to this to reproduce reliably. Going back and forth between the two vloopers loopers and testing them, these pop up sometimes. One outcome is the Vlooper becomes unresponsive to both Vlooper controls and character gesture keys.

See attached log.

[output_log_local_vloopers_produce_keynotFoundExceptions.txt](https://github.com/mdotstrange/NightmarePuppeteerPublic/files/5037099/output_log_local_vloopers_produce_keynotFoundExceptions.txt)

**Comment by mdotstrange** [comment]
Yeh I've got this one too randomly and its tough for me to figure out- I'll take a look at it again- need to get rid of the error for sure

**Comment by mdotstrange** [comment]
Don't know if its connected but noticed Start recording also plays the loopers buffer if it has one which is not a desired behavior-

**Comment by mdotstrange** [comment]
Decided to go with clear loop and record new one if its playing and you hit record- punching in is too advanced for me 0_0 and AH I did find Looper2 was checking Looper1 when it should have been checking itself- ALSO found when checking to see if the index of the list was valid was using List.Count instead of List.Count -1 - that human counting messing me up again 0_0 Hope this fixes it- going to test now

**Comment by mdotstrange** [comment]
Did some work on this one- haven't gotten it again while testing today but going to keep it open as I bet its a nagging on 0_0

**Comment by mdotstrange** [comment]
The recent VLooper bug fix should have resolved this one as well- closing this-
