### ISSUE TITLE
using a lot of ram

### ISSUE THREAD

**Issue by Jolsh2** [mdotstrange/NightmarePuppeteerPublic#312]
recently happened. windows 10 recent update too. maybe thats it...

![image](https://user-images.githubusercontent.com/71854487/112739348-b9ee9900-8f41-11eb-85c5-02ea6dc5d888.png)

game crash. thoughts?

**Comment by mdotstrange** [comment]
4-5gb of Ram would be a lot for a game but not an application like this-  the hanging/crashing I'm not sure about- BUT a user had an issue where NP was crashing because it ate all his RAM because it was loading in a bunch of big audio files from the Audio Recorder- do you use the Audio recorder audio file list to load files into a lot?

If so I can tell you how to clear it and I will add this to the manual-

**Comment by Jolsh2** [comment]
I deleted all theos wav files. Ended being a good amount of space removed. But didn't resolve. The game uses a lot of ram right after you select the language. Weird too my steam won't let me install new games in the 'desktop' mode but let's me install in the big picture mode. So I deleted NP deleted any files I saw in my drives and reinstalled. Didn't work. So then I deleted steam and reinstalled steam and NP. Didn't work.
I last was using it 2/26/21 around 9 or 10p eastern. Didnt work next day... Wander what gapped between then. Also I was having issues earlier on 2/26/21. Idk I'll have to do some digging. I did see updates on some things on 2/27 when I discovered the issue. Maybe I can revert to that day to see if anything changes or something...

**Comment by mdotstrange** [comment]
Sounds like it could be a Windows/Steam thing- I disabled Windows10 updates as I don't trust those things to not break stuff- also when you search for Steam errors there's lots of weird Steam issues that popup-

I didn't change anything recently that should affect NP's memory usage but I'll take a look at it-

**Comment by Jolsh2** [comment]
thx. after a ton of crashes i was able to get in and and able to get in repeatedly. Weird thing is that now it crashes once then it works the second try. Im sitting at this level right now (jpg). Gets up to 99% GPU. sometimes. I just wish i was able to compare to the other day what the values where. drivers seems to be updated. its running what seems to be fine. IDK some weird stuff was happening to the comp in the last few days... ill let you know if the crashing issue persists. 

![image](https://user-images.githubusercontent.com/71854487/112782167-68fea380-901a-11eb-838a-5ac2f0eaf10d.png)

and again thanks, Definitely top 5 favorite "games". i find it hard in my spare time to play single player or non creative games now :).

**Comment by SameSkeletonDifferentCloset** [comment]
Windows 10 is quite buggy but the first launch crash happens 9 out of 10 times for me. Sometimes It can take 6 or more crashes before I can get it. This has also happened for me on an older laptop with Windows 7. My laptop can handle the requirements for NP but one of the reasons I leave NP running in the background sometimes is because of the crashing. Reminds me of when Diablo 3 got The expansion. My laptop then wasn't a gaming one. It'd take so long to load that when it did load me in town it was like delayed and would immediately kick me out. Kind of reminds me of after selecting the language I get to the black screen and it hangs for a few seconds and I brace myself for it to crash. 

I wonder if there could be a version without the twitch part that if I remember correctly is why you can't minimize NP.

**Comment by Jolsh2** [comment]
i get the crash right after the language screen but before clicking the sprite face to bring you to the 
its just annoying cuz it started all of a sudden. there were only three things that happened to my knowledge the day prior. install of autocad 2021, reinstall of office 365, and update of windows. And it doesn't seem like windows allows you to really restore anymore. i clicked the box to "run as administrator" in the properties. it made it not crash, but i haven't tested it enough. will see...
im on a windows surface book 2. so it has a dedicated GPU but probably not "gaming" quality. i can run some things though. havent tried anything that really need a lot of resources as i have an xbox and always had bad experiences with computer gaming and Frames and quality which probably discourages me. plus im too busy lol. ok end of story.

**Comment by Jolsh2** [comment]
haha ok, so i uninstalled the last windows update and reinstalled with the optional updates. and that fixed both my explorer issue i was having. and i just had ANOTHER windows update. My IT said Microsoft really messed up their recent updates. anyways now when i play my GPU gets super hot and the fan is like a jet engine. I cant win.... fun stuff.

**Comment by mdotstrange** [comment]
I didn't do any updates but even so I had to disable Windows defender realtime threat processing or whatever it is called as it was throttling my GPU at random times which really messed up performance- I went through a bunch of articles and youtube vids showing you how to disable a bunch of useless crap that eats memory and gpu performance on Win 10- might want to check that stuff out-

**Comment by Jolsh2** [comment]
https://answers.microsoft.com/en-us/surface/forum/surfacebook-surfver_surfbook2-surftop_install/surface-book-2-gpu-fan-speed-bug-after-april-2021/ac33c7f1-9ab1-47c1-98f9-f379609466d0

"Its me... not you...."

MICROSOFTTTT.    i think they bettered the RAM portion of it as now it uses 2gb instead of 5 previously for the same graphics selection and resolution size. but i feel like I'm piloting a aircraft without a windshield.
